namespace GraphDLL
{
    internal enum FuncTypes
    {
        wait, fullscreen, windowscreen,
        showmouse, hidemouse, refresh, mouse3da,
        close
    }

    public enum FontStyle
    {
        Bold = System.Drawing.FontStyle.Bold,
        Italic = System.Drawing.FontStyle.Italic,
        Regular = System.Drawing.FontStyle.Regular,
        Strikeout = System.Drawing.FontStyle.Strikeout,
        Underline = System.Drawing.FontStyle.Underline
    }

    public enum AnaglyphMethod { True, Gray, Color, HalfColor, Optimized }

    public enum Glass { None, Anaglyph, TV3D }

    public enum Surface { XY, XZ, YZ }

    public enum MIDIInstruments
    {
        AcousticGrand = 0,
        BrightAcoustic = 1,
        ElectricGrand = 2,
        HonkyTonk = 3,
        ElectricPiano1 = 4,
        ElectricPiano2 = 5,
        Harpsichord = 6,
        Clav = 7,
        Celesta = 8,
        Glockenspiel = 9,
        MusicBox = 10,
        Vibraphone = 11,
        Marimba = 12,
        Xylophone = 13,
        TubularBells = 14,
        Dulcimer = 15,
        DrawbarOrgan = 16,
        PercussiveOrgan = 17,
        RockOrgan = 18,
        ChurchOrgan = 19,
        ReedOrgan = 20,
        Accoridan = 21,
        Harmonica = 22,
        TangoAccordian = 23,
        NylonAcousticGuitar = 24,
        SteelAcousticGuitar = 25,
        JazzElectricGuitar = 26,
        CleanElectricGuitar = 27,
        MutedElectricGuitar = 28,
        OverdrivenGuitar = 29,
        DistortionGuitar = 30,
        GuitarHarmonics = 31,
        AcousticBass = 32,
        FingerElectricBass = 33,
        PickElectricBass = 34,
        FretlessBass = 35,
        SlapBass1 = 36,
        SlapBass2 = 37,
        SynthBass1 = 38,
        SynthBass2 = 39,
        Violin = 40,
        Viola = 41,
        Cello = 42,
        Contrabass = 43,
        TremoloStrings = 44,
        PizzicatoStrings = 45,
        OrchestralStrings = 46,
        Timpani = 47,
        StringEnsemble1 = 48,
        StringEnsemble2 = 49,
        SynthStrings1 = 50,
        SynthStrings2 = 51,
        ChoirAahs = 52,
        VoiceOohs = 53,
        SynthVoice = 54,
        OrchestraHit = 55,
        Trumpet = 56,
        Trombone = 57,
        Tuba = 58,
        MutedTrumpet = 59,
        FrenchHorn = 60,
        BrassSection = 61,
        SynthBrass1 = 62,
        SynthBrass2 = 63,
        SopranoSax = 64,
        AltoSax = 65,
        TenorSax = 66,
        BaritoneSax = 67,
        Oboe = 68,
        EnglishHorn = 69,
        Bassoon = 70,
        Clarinet = 71,
        Piccolo = 72,
        Flute = 73,
        Recorder = 74,
        PanFlute = 75,
        BlownBottle = 76,
        Skakuhachi = 77,
        Whistle = 78,
        Ocarina = 79,
        SquareLead = 80,
        SawtoothLead = 81,
        CalliopeLead = 82,
        ChiffLead = 83,
        CharangLead = 84,
        VoiceLead = 85,
        FifthsLead = 86,
        BaseLead = 87,
        NewAgePad = 88,
        WarmPad = 89,
        PolysynthPad = 90,
        ChoirPad = 91,
        BowedPad = 92,
        MetallicPad = 93,
        HaloPad = 94,
        SweepPad = 95,
        Rain = 96,
        Soundtrack = 97,
        Crystal = 98,
        Atmosphere = 99,
        Brightness = 100,
        Goblin = 101,
        Echos = 102,
        SciFi = 103,
        Sitar = 104,
        Banjo = 105,
        Shamisen = 106,
        Koto = 107,
        Kalimba = 108,
        Bagpipe = 109,
        Fiddle = 110,
        Shanai = 111,
        TinkleBell = 112,
        Agogo = 113,
        SteelDrums = 114,
        Woodblock = 115,
        TaikoDrum = 116,
        MelodicTom = 117,
        SynthDrum = 118,
        ReverseCymbal = 119,
        GuitarFretNoise = 120,
        BreathNoise = 121,
        Seashore = 122,
        BirdTweet = 123,
        TelephoneRing = 124,
        Helicopter = 125,
        Applause = 126,
        Gunshot = 127,
    }
}
